influxdb:
  bucket: "XXX/YYY"
  org: "ZZZ"
  token: "uuuuuu"
  url: "https://xxx"

Location:
  proj: 'utm'
  zone: 30
  ellps: 'WGS84'
  south: False
  code: 'epsg:4326'
  zoneInfo: 'Europe/Madrid'

Display:
  mode:'Screen'  # 'PDF'